"""
This is a setup.py script generated by py2app

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os
from app.constants import APP_NAME, APP_VERSION, APP_BUILD_NUMBER

# --- Configuration ---
APP = ['main.py']
APP_NAME_STR = APP_NAME
APP_VERSION_STR = f"{APP_VERSION}"
APP_BUILD_STR = str(APP_BUILD_NUMBER)
BUNDLE_ID = 'com.cr2creative.echelon'
ICON_FILE = 'Icons/Echelon.icns'
DEV_ID = 'Developer ID Application: craig russo (5926DW86QY)'

# Data files to include
DATA_FILES = [
    'Icons',
    ('app', [
        'app/assets',
        'app/templates'
    ]),
    ('', ['EULA.txt'])
]

# Options for py2app
OPTIONS = {
    'argv_emulation': True,
    'iconfile': ICON_FILE,
    'plist': {
        'CFBundleName': APP_NAME_STR,
        'CFBundleDisplayName': APP_NAME_STR,
        'CFBundleShortVersionString': APP_VERSION_STR,
        'CFBundleVersion': APP_BUILD_STR,
        'CFBundleIdentifier': BUNDLE_ID,
        'LSMinimumSystemVersion': '11.0',
        'NSHumanReadableCopyright': 'Copyright © 2023-present Craig P. Russo and CR2 Creative. All rights reserved.',
        'NSPrincipalClass': 'NSApplication',
        'NSAppleScriptEnabled': False,
        'NSHighResolutionCapable': True,
    },
    'packages': ['app', 'requests'], 
    'includes': [ 
        # Explicitly include modules that might be missed but are imported in main.py or dependencies
        'PyQt5.QtWidgets', 
        'PyQt5.QtCore', 
        'PyQt5.QtGui',
        'app.core.app_module_pyqt',
        'app.config.app_config',
        'app.ui.app_theme_pyqt',
        'app.templates.template_manager_migration',
        'app.ui.tree_styling',
        'app.utils.security.license_manager',
        'json',
        'webbrowser',
        'platform',
        'os',
        'sys',
        'ctypes',
        'traceback',
        'requests.adapters', # Often needed by requests
        'packaging' # Added for version comparison
    ], 
    'excludes': [
        # Keep aggressive excludes for large libraries
        'tkinter',
        'unittest',
        'numpy',
        'pandas',
        'matplotlib',
        'scipy',
        'pytest',
        # 'PyQt5', # Reverted: Add PyQt5 to general excludes
        
        # Aggressively exclude specific PyQt5 modules NOT directly used in main.py or known dependencies
        'PyQt5.Qsci',
        'PyQt5.QtDesigner',
        'PyQt5.QtHelp',
        'PyQt5.QtNetwork', # Excluded as requests should handle networking
        'PyQt5.QtMultimedia',
        'PyQt5.QtMultimediaWidgets',
        'PyQt5.QtOpenGL', # Assuming no direct OpenGL usage
        'PyQt5.QtPrintSupport', # Assuming no printing
        'PyQt5.QtSql', # Assuming no SQL usage
        'PyQt5.QtSvg', # Include via qt_plugins instead
        'PyQt5.QtTest',
        'PyQt5.QtWebChannel',
        'PyQt5.QtWebEngineCore',
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtWebKit',
        'PyQt5.QtWebKitWidgets',
        'PyQt5.QtXml',
        'PyQt5.QtXmlPatterns',
        'PyQt5.QtBluetooth',
        'PyQt5.QtNfc',
        'PyQt5.QtSerialPort',
        'PyQt5.QtLocation',
        'PyQt5.QtPositioning',
        'PyQt5.QtSensors',
        'PyQt5.QtQuick',
        'PyQt5.QtQuickWidgets',
        'PyQt5.Qml',
    ],
    'arch': 'arm64',
    'optimize': 2,
    'strip': True,
    'site_packages': False,
    'semi_standalone': False,
    'bdist_base': 'MAC BUILD/build',
    'dist_dir': 'MAC BUILD/dist',
    'qt_plugins': [ # Explicitly include necessary Qt plugins
        'platforms/libqcocoa.dylib',
        'imageformats/libqgif.dylib',
        'imageformats/libqicns.dylib',
        'imageformats/libqico.dylib',
        'imageformats/libqjpeg.dylib',
        'imageformats/libqsvg.dylib',
        'imageformats/libqtiff.dylib',
        'imageformats/libqwbmp.dylib',
        'styles/libqmacstyle.dylib',
        'iconengines/libqsvgicon.dylib'
    ]
}

# --- Setup Call ---
setup(
    app=APP,
    name=APP_NAME_STR,
    version=f"{APP_VERSION_STR}.{APP_BUILD_STR}",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)