"""
This setup.py is generated by py2app for building the Echelon app for macOS.
It includes only the essential components to reduce the final application size.
"""

from setuptools import setup

APP_NAME = 'Echelon'
APP = ['../main.py']
DATA_FILES = []
ICON_FILE = '../ICONS/Echelon.icns'

# Only include necessary packages
PACKAGES = ['PyQt5', 'app', 'json', 'webbrowser']

# Only include the essential PyQt modules
INCLUDES = [
    'PyQt5',
    'PyQt5.QtCore',
    'PyQt5.QtGui',
    'PyQt5.QtWidgets',
    'PyQt5.QtPrintSupport',
]

# Exclude unnecessary modules to reduce size
EXCLUDES = [
    'numpy', 'scipy', 'matplotlib', 'pandas', 'PIL', 'tkinter',
    'test', 'unittest', 'doctest', 'pdb', 'difflib', 'pydoc',
    'PyQt5.QtWebEngine', 'PyQt5.QtWebEngineCore', 'PyQt5.QtWebEngineWidgets',
    'PyQt5.QtQuick', 'PyQt5.QtQuickWidgets', 'PyQt5.QtQml',
    'PyQt5.QtMultimedia', 'PyQt5.QtMultimediaWidgets',
    'PyQt5.QtBluetooth', 'PyQt5.QtSensors', 'PyQt5.QtSerialPort',
    'PyQt5.QtDesigner', 'PyQt5.QtHelp', 'PyQt5.QtLocation',
    'PyQt5.QtNfc', 'PyQt5.QtPositioning', 'PyQt5.QtSvg',
    'PyQt5.QtTest', 'PyQt5.QtWebChannel', 'PyQt5.QtXml',
    'PyQt5.QtXmlPatterns', 'PyQt5.QtSql'
]

OPTIONS = {
    'argv_emulation': True,
    'iconfile': ICON_FILE,
    'packages': PACKAGES,
    'includes': INCLUDES,
    'excludes': EXCLUDES,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleIdentifier': 'com.echelon.app',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHumanReadableCopyright': '© 2023 Echelon',
        'NSPrincipalClass': 'NSApplication',
        'NSHighResolutionCapable': True,
    },
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)